In [1]:
import random 

In [2]:
random.randint(–90, 90)

SyntaxError: invalid character in identifier (<ipython-input-2-83a0e0bb4a92>, line 1)

In [3]:
random.random()

0.4350656968664467

In [4]:
random_number = random.randint(–90, 89) + random.random()

SyntaxError: invalid character in identifier (<ipython-input-4-d4791086e99f>, line 1)

In [5]:
x = 1
latitudes = []
while x < 11:
    random_lat = random.randint(-90, 89) + random.random()
    latitudes.append(random_lat)
    x += 1


In [6]:
x

11

In [7]:
random.randrange(-90, 90, step=1)

88

In [8]:
random.randrange(-90, 90, step=3)

48

In [9]:
random.uniform(-90, 90)

10.243414418032572

In [10]:
# Import the NumPy module.
import numpy as np


In [11]:
np.random.uniform(-90.000, 90.000)

-42.11116227833107

In [12]:
np.random.uniform(low=-90, high=90)

-33.08128031960051

In [13]:
np.random.uniform(-90.000, 90.000, size=50)

array([  6.76474442,  71.70653004, -49.74638295, -52.37995403,
         7.62631164, -89.96478929,  74.32866763,  -8.86175554,
       -71.63900503,  50.10118336, -18.01799938,  58.39382344,
       -52.77317922,  17.37659092, -85.92016271, -33.59864766,
       -57.66241191,  39.34041794,  49.86126049, -12.81627925,
       -10.52502031, -74.80598646,  61.44403008, -89.0220747 ,
        66.38975685,  62.11227016, -12.07280696,   5.22971383,
         8.52706145,  71.25678447,  70.66766783, -77.92187232,
       -30.81624716, -61.94494826, -85.31388516,   3.29355089,
       -61.07493223,  75.40647836,  -9.83847513,  21.47269938,
        73.2127713 ,  83.79665985, -51.11385623, -29.00067721,
        89.16999186,  27.69210569, -25.96828693, -35.74573118,
         3.18817332,  34.6924661 ])

In [14]:
# Import timeit.
import timeit


In [15]:
%timeit np.random.uniform(-90.000, 90.000, size=1500)


14.9 µs ± 965 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [16]:
def latitudes(size):
    latitudes = []
    x = 0
    while x < (size):
        random_lat = random.randint(-90, 90) + random.random()
        latitudes.append(random_lat)
        x += 1
    return latitudes
# Call the function with 1500.
%timeit latitudes(1500)

1.45 ms ± 111 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
np.random.uniform(-90.000, 90.000, size=1500)

array([ 72.47769174,  76.35053219, -32.39873325, ...,  -0.41170699,
       -49.60495707, -22.24706334])

In [18]:
np.random.uniform(-90.000, 90.000, size=1500)

array([ 17.29422897,  -1.5804487 , -38.93759695, ..., -85.95408746,
        62.85565731,  25.97775219])